// Code generated by goyacc expr.y. DO NOT EDIT.

//line expr.y:2
package main

import __yyfmt__ "fmt"

//line expr.y:2

import "fmt"

var _ = fmt.Sprint

//line expr.y:9
type yySymType struct {
	yys  int
	node *ExprNode
}

const NUM = 57346

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUM",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line expr.y:37

type exprLex struct {
	tokens []string
	pos    int
}

func (p *exprLex) read() (tok string) {
	if p.pos >= len(p.tokens) {
		return ""
	}
	tok = p.tokens[p.pos]
	p.pos++
	return
}

func (p *exprLex) Lex(yylval *yySymType) int {
	switch s := p.read(); s {
	case "+", "-", "*", "/", "(", ")":
		return int(s[0])
	default:
		if s != "" {
			yylval.node = NewExprNode(s, nil, nil)
			return NUM
		}
		return 0
	}
}

func (x *exprLex) Error(s string) {
	panic(s)
}

func ParseExpr(tokens []string) *ExprNode {
	parser := yyNewParser().(*yyParserImpl)
	parser.Parse(&exprLex{tokens: tokens})
	return parser.lval.node
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 18

var yyAct = [...]int{
	7, 8, 4, 5, 2, 16, 3, 1, 6, 9,
	10, 11, 14, 15, 12, 13, 7, 8,
}

var yyPact = [...]int{
	-1, -1000, 11, 2, -1000, -1000, -1, -1, -1, -1,
	-1, -5, 2, 2, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 4, 6, 2, 7,
}

var yyR1 = [...]int{
	0, 4, 1, 1, 1, 2, 2, 2, 3, 3,
}

var yyR2 = [...]int{
	0, 1, 1, 3, 3, 1, 3, 3, 1, 3,
}

var yyChk = [...]int{
	-1000, -4, -1, -2, -3, 4, 9, 5, 6, 7,
	8, -1, -2, -2, -3, -3, 10,
}

var yyDef = [...]int{
	0, -2, 1, 2, 5, 8, 0, 0, 0, 0,
	0, 0, 3, 4, 6, 7, 9,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	9, 10, 7, 5, 3, 6, 3, 8,
}

var yyTok2 = [...]int{
	2, 3, 4,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
	Debug() int
	ErrorVerbose() bool
	SetDebug(level int)
	SetErrorVerbose(verbose bool)
}

type yyParserImpl struct {
	lval         yySymType
	stack        [yyInitialStackSize]yySymType
	char         int
	debug        int
	errorVerbose bool
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func (p *yyParserImpl) Debug() int {
	return p.debug
}

func (p *yyParserImpl) SetDebug(level int) {
	p.debug = level
}

func (p *yyParserImpl) ErrorVerbose() bool {
	return p.errorVerbose
}

func (p *yyParserImpl) SetErrorVerbose(verbose bool) {
	p.errorVerbose = verbose
}

func yyNewParser() yyParser {
	return &yyParserImpl{
		debug:        yyDebug,
		errorVerbose: yyErrorVerbose,
	}
}

func yyNewParserExt(debug int, errorVerbose bool) yyParser {
	return &yyParserImpl{
		debug:        debug,
		errorVerbose: errorVerbose,
	}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func (yyrcvr *yyParserImpl) yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyrcvr.errorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func (yyrcvr *yyParserImpl) yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyrcvr.debug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func yyParseExt(debug int, errorVerbose bool, yylex yyLexer) int {
	return yyNewParserExt(debug, errorVerbose).Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyrcvr.debug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yyrcvr.yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yyrcvr.yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyrcvr.yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyrcvr.debug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyrcvr.debug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyrcvr.debug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyrcvr.debug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:24
		{
			yyrcvr.lval.node = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:26
		{
			yyVAL.node = yyDollar[1].node
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:27
		{
			yyVAL.node = NewExprNode("+", yyDollar[1].node, yyDollar[3].node)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:28
		{
			yyVAL.node = NewExprNode("-", yyDollar[1].node, yyDollar[3].node)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:30
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:31
		{
			yyVAL.node = NewExprNode("*", yyDollar[1].node, yyDollar[3].node)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:32
		{
			yyVAL.node = NewExprNode("/", yyDollar[1].node, yyDollar[3].node)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:34
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:35
		{
			yyVAL.node = yyDollar[2].node
		}
	}
	goto yystack /* stack new state and value */
}
